# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    vector_skin:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: "Clone vector skin repository"
              run: |
                  git clone "https://gerrit.wikimedia.org/r/mediawiki/skins/Vector" skins/Vector
            - name: "Add vector skin config to LocalSettings.php file"
              run: |
                  echo "wfLoadSkin( 'Vector' );" >> LocalSettings.php

    test:
        env:
            MW_DOCKER_PORT: 8080
            MW_SCRIPT_PATH: /w
            MW_SERVER: http://localhost:8080
            MEDIAWIKI_USER: Admin
            MEDIAWIKI_PASSWORD: dockerpass
            XDEBUG_CONFIG: ""
        runs-on: ubuntu-latest
        needs: vector_skin

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: "Install dependencies"
              run: |
                  npm ci
            - name: "Run eslint"
              run: |
                  npm run lint
            - name: Setup mediawiki-docker
              run: |
                  docker-compose up -d
                  docker ps -a
            - name: "Run playwright tests"
              run: |
                  npm run playwright:silent
