name: Test CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Create .env file
              run: "${GITHUB_WORKSPACE}/.github/scripts/environment.sh"
              shell: bash
            - uses: actions/checkout@master
            - uses: nanasess/setup-chromedriver@master
            - run: chromedriver --url-base=wd/hub --port=4444 &
            - name: Create docker-compose.override.yml
              run: "${GITHUB_WORKSPACE}/.github/scripts/docker-compose.override.sh"
              shell: bash
            - name: Start Mediawiki-docker
              run: |
                  docker-compose up -d
                  docker-compose exec -T mediawiki composer update
                  docker-compose exec -T mediawiki /bin/bash /docker/install.sh
            - name: Clone skins/Vector
              run: git clone "https://gerrit.wikimedia.org/r/mediawiki/skins/Vector" skins/Vector
            - name: Setup LocalSettings.php
              run: echo "wfLoadSkin( 'Vector' );" >> LocalSettings.php
            - name: Setup Nodejs
              uses: actions/setup-node@v1
              with:
                  node-version: "10.x"
            - name: Install dependencies & Run eslint
              run: |
                  npm ci
                  npm run lint
            - name: Run playwright tests
              run: |
                  npm run playwright:silent
            - uses: actions/upload-artifact@v2
              name: Upload playwright artifacts
              with:
                  name: playwright-artifact
                  path: tests/playwright/log
                  retention-days: 2
            - name: Run webdriver.io tests
              run: npm run selenium-test
            - uses: actions/upload-artifact@v2
              name: Upload selenium artifacts
              with:
                  name: selenium-artifact
                  path: tests/selenium/log
                  retention-days: 2
